name: Notify Migration

on:
  pull_request_target:
    types:
      - opened
    paths:
      - db/migrate/*'

jobs:
  notify-tal:
    runs-on: unbuntu-latest
    run:   curl -X POST --data-urlencode "payload={\"text\": \"Connectivity test\"}" $SLACK_DEPLOY_WEBHOOK
    env:
      webhook: ${{ secrets.SLACK_WEBHOOK_URL }}

