name: Notify Migration

on:
  pull_request_target:
    types:
      - opened
    paths:
      - db/migrate/*'

jobs:
  notify-tal:
    steps:
      - name: send notification
        runs-on: unbuntu-latest
        run: curl -X POST --data-urlencode "payload={\"text\": \"Connectivity test\"}" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

