name: Notify Migration

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'db/migrate/*'
      - 'db/schema.rb'
jobs:
  run:
    name: notify-slack-help-data-pod-channel
    runs-on: ubuntu-latest
    env:
      SLACK_DB_MIGRATION_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_HTML_URL: ${{ github.event.pull_request.html_url }}
      PR_BODY: ${{ github.event.pull_request.body }}    
    steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: webhook-trigger
        payload: |
          blocks:  
            - type: "section"
              text:
                type: "mrkdwn"
                text: (*${{ env.PR_TITLE }}*)[${{ env.PR_HTML_URL }}]
            - type: "divider"
            - type: "section"
              text:
                type: "mrkdwn"
                text: ${{ env.PR_BODY }}




  # steps:
  #       - name: send notification
  #         run: |
  #           curl -X POST --data-urlencode "payload={\"text\": \"*$PR_TITLE*\n$PR_BODY\n$PR_HTML_URL\"}" $SLACK_DB_MIGRATION_URL