jobs:
  run:
    name: notify-slack-help-data-pod-channel
    runs-on: ubuntu-latest
    env:
      SLACK_DB_MIGRATION_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.event.pull_request.body }}"
                }
              }
            ]
          }
