name: Notify Migration

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'db/migrate/*'
      - 'db/schema.rb'

jobs:
  run:
    name: notify-slack-help-data-pod-channel
    runs-on: ubuntu-latest
    steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ toJson(github.event.pull_request.body) }}"
                }
              }
            ]
          }
