name: Notify Migration

on:
  pull_request_target:
    types: [opened, reopened]
    paths:
      - 'db/migrate/*'

jobs:
  notify-tal:
    runs-on: ubuntu-latest
    steps:
      - name: send notification
        # run: bash scripts/send_message.sh
        run: |
          ls
          pwd
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

