name: Notify Migration

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - 'db/migrate/*'
      - 'db/schema.rb'
jobs:
  notify-slack-help-data-pod-channel:
    uses: slackapi/slack-github-action@v1.26.0
    with:
      payload: |
        {
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*\"${{ env.PR_TITLE }}\"*"
              }
              ]
            }
          ]
        }
      env:
        SLACK_DB_MIGRATION_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_HTML_URL: ${{ github.event.pull_request.html_url }}
        PR_BODY: ${{ github.event.pull_request.body }}


# steps:
#       - name: send notification
#         run: |
#           curl -X POST --data-urlencode "payload={\"text\": \"*$PR_TITLE*\n$PR_BODY\n$PR_HTML_URL\"}" $SLACK_DB_MIGRATION_URL